package rules.advertisement;

import com.sbnz.adsys.model.*;
import com.sbnz.adsys.event.*;

global com.sbnz.adsys.service.SocialMediaUserService socialMediaUserService;


rule "Ad has been seen"
    when
       $adEvent : AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser)
    then
        socialMediaUserService.adSeenByUser($ad, $user);
end


rule "Ad has been clicked within 10 minutes"
    when
       $adEvent : AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser)
       AdvertisementClickEvent (advertisement.getId() == $ad.getId(),
        socialMediaUser.getUser().getId() == $user.getUser().getId(),
       this after[0s,10m] $adEvent )
    then
        socialMediaUserService.adClickedByUser($ad, $user);
end


rule "Ad has not been clicked for more than 10 mins"
    when
       $adEvent : AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser)
       not AdvertisementClickEvent (advertisement.getId() == $ad.getId(),
        socialMediaUser.getUser().getId() == $user.getUser().getId(),
       this after[0s,10m] $adEvent )
    then
        socialMediaUserService.adIgnoredByUser($ad, $user);
end