package rules.advertisement;

import com.sbnz.adsys.model.*;
import com.sbnz.adsys.event.*;

global com.sbnz.adsys.service.SocialMediaUserService socialMediaUserService;


rule "Ad has been seen"
    when
       $adEvent : AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser)
    then
        socialMediaUserService.adSeenByUser($ad, $user);
end


rule "Ad has been clicked within 10 minutes"
    when
       $adEvent : AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser)
       $ace: AdvertisementClickEvent (advertisement.getId() == $ad.getId(),
        socialMediaUser.getUser().getId() == $user.getUser().getId(),
       this after[0s,10m] $adEvent )
    then
        delete($ace);
        delete($adEvent);
        socialMediaUserService.adClickedByUser($ad, $user);
end


rule "Ad has not been clicked for more than 10 mins"
    when
       $adEvent : AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser)
       not ( AdvertisementClickEvent (advertisement.getId() == $ad.getId(),
        socialMediaUser.getUser().getId() == $user.getUser().getId(),
       this after[0s,10m] $adEvent ))
    then
        socialMediaUserService.adIgnoredByUser($ad, $user);
        System.out.println("NIJE KLIKNUTA U ZADNJIJA 10 min");
        delete($adEvent);

end

rule "Ad was clicked for more than 10 times in the last 10min"
    when
        $aie: AdvertisementClickEvent($ad: advertisement, $user: socialMediaUser)
        Number(intValue >= 20) from accumulate(
           $cavc: AdvertisementClickEvent(advertisement.getId() == $ad.getId(), socialMediaUser.getId() == $user.getId())
           over window:time(2s), count($cavc)
        )
    then
        System.out.println("NIJE KLIKNUTA U ZADNJIJAAAAAA 10 min");
        delete($aie);
        socialMediaUserService.adIgnoredByUser($ad, $user);
end

/*rule "Ad was viewed for more than 10 times in the last 10min"
      when

          AdvertisementViewEvent($ad: advertisement, $user: socialMediaUser, !isClicked());

          Number(intValue >= 10) from accumulate(
              $cavc: AdvertisementViewEvent(advertisement.getId() == $ad.getId(), socialMediaUser.getId() == $user.getId(), !isClicked()) over window:length(10),
              count($cavc)
          );
      then
          System.out.println("NIJE KLIKNUTA U ZADNJIJAAAAAA 10 min");
          delete($aie);
          socialMediaUserService.adIgnoredByUser($ad, $user);
  end*/