package rules;
import com.sbnz.adsys.utils.Constants;
import com.sbnz.adsys.DroolsTest.Message;

import  com.sbnz.adsys.model.Candidate;
import com.sbnz.adsys.model.AdvertisementRequest;

rule "Target Group Age"
    when
        $req: AdvertisementRequest($min: minAge, $max: maxAge)
        $c : Candidate(user.age > $min, user.age < $max)
    then
        System.out.println("Candidate with name: " + $c.getUser().fullName() + " satisfies the age condition");
        $c.setAgeGroup(true);
        update($c);
end


rule "Target Group Geography"
    when
        $req: AdvertisementRequest($query: geographicLocation)
        $c: Candidate(user.fullLocation.contains($query))
    then
        System.out.println("Candidate with name: " + $c.getUser().fullName() + " satisfies the geography condition");
        $c.setGeographyGroup(true);
        update($c);
end


rule "Target Group All Conditions Satisfied"
    when
        $c: Candidate(ageGroup && geographyGroup)
    then
        System.out.println("Candidate with name: " + $c.getUser().fullName() + " does belong to ad target group!");
        $c.setTargetGroup(true);
        update($c);
end